# Generated by Django 5.0.6 on 2024-06-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='编码')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路径')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='组件')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('show', models.BooleanField(default=True, verbose_name='显示')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('layout', models.CharField(blank=True, max_length=50, null=True, verbose_name='布局')),
                ('keepAlive', models.BooleanField(default=False, verbose_name='KeepAlive')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu', verbose_name='父级菜单')),
            ],
        ),
    ]
